import turtle as trt
import math


def zero():
    trt.pendown()
    trt.forward(10)
    trt.left(90)
    trt.forward(20)
    trt.left(90)
    trt.forward(10)
    trt.left(90)
    trt.forward(20)
    trt.penup()
    trt.left(90)
    trt.forward(15)


def one():
    trt.penup()
    trt.forward(10)
    trt.left(90)
    trt.pendown()
    trt.forward(20)
    trt.left(135)
    trt.forward(math.sqrt(2) * 10)
    trt.left(45)
    trt.penup()
    trt.forward(10)
    trt.left(90)
    trt.forward(15)


def two():
    trt.penup()
    trt.left(90)
    trt.forward(20)
    trt.pendown()
    trt.right(90)
    trt.forward(10)
    trt.right(90)
    trt.forward(10)
    trt.right(45)
    trt.forward(math.sqrt(2) * 10)
    trt.left(135)
    trt.forward(10)
    trt.penup()
    trt.forward(5)


def three():
    trt.pendown()
    trt.left(45)
    trt.forward(math.sqrt(2) * 10)
    trt.left(135)
    trt.forward(10)
    trt.right(135)
    trt.forward(math.sqrt(2) * 10)
    trt.left(135)
    trt.forward(10)
    trt.penup()
    trt.left(90)
    trt.forward(20)
    trt.left(90)
    trt.forward(15)


def four():
    trt.penup()
    trt.forward(10)
    trt.pendown()
    trt.left(90)
    trt.forward(20)
    trt.backward(10)
    trt.left(90)
    trt.forward(10)
    trt.right(90)
    trt.forward(10)
    trt.penup()
    trt.backward(20)
    trt.right(90)
    trt.forward(15)


def five():
    trt.pendown()
    trt.forward(10)
    trt.left(90)
    trt.forward(10)
    trt.left(90)
    trt.forward(10)
    trt.right(90)
    trt.forward(10)
    trt.right(90)
    trt.forward(10)
    trt.penup()
    trt.right(90)
    trt.forward(20)
    trt.left(90)
    trt.forward(5)


def six():
    trt.pendown()
    trt.forward(10)
    trt.left(90)
    trt.forward(10)
    trt.left(90)
    trt.forward(10)
    trt.left(90)
    trt.forward(10)
    trt.left(180)
    trt.forward(10)
    trt.right(45)
    trt.forward(math.sqrt(2) * 10)
    trt.penup()
    trt.right(135)
    trt.forward(20)
    trt.left(90)
    trt.forward(5)


def seven():
    trt.pendown()
    trt.left(90)
    trt.forward(10)
    trt.right(45)
    trt.forward(math.sqrt(2) * 10)
    trt.left(135)
    trt.forward(10)
    trt.penup()
    trt.left(90)
    trt.forward(20)
    trt.left(90)
    trt.forward(15)


def eight():
    trt.pendown()
    trt.forward(10)
    trt.left(90)
    trt.forward(20)
    trt.left(90)
    trt.forward(10)
    trt.left(90)
    trt.forward(20)
    trt.backward(10)
    trt.left(90)
    trt.forward(10)
    trt.penup()
    trt.right(90)
    trt.forward(10)
    trt.left(90)
    trt.forward(5)


def nine():
    trt.pendown()
    trt.left(45)
    trt.forward(math.sqrt(2) * 10)
    trt.left(45)
    trt.forward(10)
    trt.left(90)
    trt.forward(10)
    trt.left(90)
    trt.forward(10)
    trt.left(90)
    trt.forward(10)
    trt.penup()
    trt.right(90)
    trt.forward(10)
    trt.left(90)
    trt.forward(5)
